export interface OpecodeProps {
  fullName: string
  commandName: BaseName
  mode: AddressingMode
  cycle: number
}

export const enum AddressingMode {
  ZERO_PAGE = 'zeroPage',
  RELATIVE = 'relative',
  IMPLIED = 'implied',
  ABSOLUTE = 'absolute',
  ACCUMULATOR = 'accumulator',
  IMMEDIATE = 'immediate',
  ZERO_PAGE_X = 'zeroPageX',
  ZERO_PAGE_Y = 'zeroPageY',
  ABSOLUTE_X = 'absoluteX',
  ABSOLUTE_Y = 'absoluteY',
  PRE_INDEXED_INDIRECT = 'preIndexedIndirect',
  POST_INDEXED_INDIRECT = 'postIndexedIndirect',
  INDIRECT_ABSOLUTE = 'indirectAbsolute',
}

export const enum BaseName {
  LDA = 'LDA',
  LDX = 'LDX',
  LDY = 'LDY',
  STA = 'STA',
  STX = 'STX',
  STY = 'STY',
  TAX = 'TAX',
  TAY = 'TAY',
  TSX = 'TSX',
  TXA = 'TXA',
  TXS = 'TXS',
  TYA = 'TYA',
  ADC = 'ADC',
  AND = 'AND',
  ASL = 'ASL',
  BIT = 'BIT',
  CMP = 'CMP',
  CPX = 'CPX',
  CPY = 'CPY',
  DEC = 'DEC',
  DEX = 'DEX',
  DEY = 'DEY',
  EOR = 'EOR',
  INC = 'INC',
  INX = 'INX',
  INY = 'INY',
  LSR = 'LSR',
  ORA = 'ORA',
  ROL = 'ROL',
  ROR = 'ROR',
  SBC = 'SBC',
  PHA = 'PHA',
  PHP = 'PHP',
  PLA = 'PLA',
  PLP = 'PLP',
  JMP = 'JMP',
  JSR = 'JSR',
  RTS = 'RTS',
  RTI = 'RTI',
  BCC = 'BCC',
  BCS = 'BCS',
  BEQ = 'BEQ',
  BMI = 'BMI',
  BNE = 'BNE',
  BPL = 'BPL',
  BVS = 'BVS',
  BVC = 'BVC',
  CLD = 'CLD',
  CLC = 'CLC',
  CLI = 'CLI',
  CLV = 'CLV',
  SEC = 'SEC',
  SEI = 'SEI',
  SED = 'SED',
  BRK = 'BRK',
  NOP = 'NOP',
  NOPD = 'NOPD',
  NOPI = 'NOPI',
  LAX = 'LAX',
  SAX = 'SAX',
  DCP = 'DCP',
  ISB = 'ISB',
  SLO = 'SLO',
  RLA = 'RLA',
  SRE = 'SRE',
  RRA = 'RRA',
}

/** 処理サイクル数 */
export const cycles = [
  /*0x00*/ 7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6, /*0x10*/ 2, 5, 2, 8,
  4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7, /*0x20*/ 6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2,
  2, 4, 4, 6, 6, /*0x30*/ 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
  /*0x40*/ 6, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 3, 4, 6, 6, /*0x50*/ 2, 5, 2, 8,
  4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7, /*0x60*/ 6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2,
  2, 5, 4, 6, 6, /*0x70*/ 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
  /*0x80*/ 2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4, /*0x90*/ 2, 6, 2, 6,
  4, 4, 4, 4, 2, 4, 2, 5, 5, 4, 5, 5, /*0xA0*/ 2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2,
  2, 4, 4, 4, 4, /*0xB0*/ 2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,
  /*0xC0*/ 2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6, /*0xD0*/ 2, 5, 2, 8,
  4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, /*0xE0*/ 2, 6, 3, 8, 3, 3, 5, 5, 2, 2, 2,
  2, 4, 4, 6, 6, /*0xF0*/ 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
]

/**
 * command対応辞書
 */
export const dict: { [code: string]: OpecodeProps } = {
  A9: {
    fullName: 'LDA_IMM',
    commandName: BaseName.LDA,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xa9],
  },
  A5: {
    fullName: 'LDA_ZERO',
    commandName: BaseName.LDA,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xa5],
  },
  AD: {
    fullName: 'LDA_ABS',
    commandName: BaseName.LDA,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xad],
  },
  B5: {
    fullName: 'LDA_ZEROX',
    commandName: BaseName.LDA,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xb5],
  },
  BD: {
    fullName: 'LDA_ABSX',
    commandName: BaseName.LDA,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xbd],
  },
  B9: {
    fullName: 'LDA_ABSY',
    commandName: BaseName.LDA,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0xb9],
  },
  A1: {
    fullName: 'LDA_INDX',
    commandName: BaseName.LDA,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0xa1],
  },
  B1: {
    fullName: 'LDA_INDY',
    commandName: BaseName.LDA,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0xb1],
  },
  A2: {
    fullName: 'LDX_IMM',
    commandName: BaseName.LDX,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xa2],
  },
  A6: {
    fullName: 'LDX_ZERO',
    commandName: BaseName.LDX,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xa6],
  },
  AE: {
    fullName: 'LDX_ABS',
    commandName: BaseName.LDX,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xae],
  },
  B6: {
    fullName: 'LDX_ZEROY',
    commandName: BaseName.LDX,
    mode: AddressingMode.ZERO_PAGE_Y,
    cycle: cycles[0xb6],
  },
  BE: {
    fullName: 'LDX_ABSY',
    commandName: BaseName.LDX,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0xbe],
  },
  A0: {
    fullName: 'LDY_IMM',
    commandName: BaseName.LDY,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xa0],
  },
  A4: {
    fullName: 'LDY_ZERO',
    commandName: BaseName.LDY,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xa4],
  },
  AC: {
    fullName: 'LDY_ABS',
    commandName: BaseName.LDY,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xac],
  },
  B4: {
    fullName: 'LDY_ZEROX',
    commandName: BaseName.LDY,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xb4],
  },
  BC: {
    fullName: 'LDY_ABSX',
    commandName: BaseName.LDY,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xbc],
  },
  '85': {
    fullName: 'STA_ZERO',
    commandName: BaseName.STA,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x85],
  },
  '8D': {
    fullName: 'STA_ABS',
    commandName: BaseName.STA,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x8d],
  },
  '95': {
    fullName: 'STA_ZEROX',
    commandName: BaseName.STA,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x95],
  },
  '9D': {
    fullName: 'STA_ABSX',
    commandName: BaseName.STA,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x9d],
  },
  '99': {
    fullName: 'STA_ABSY',
    commandName: BaseName.STA,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x99],
  },
  '81': {
    fullName: 'STA_INDX',
    commandName: BaseName.STA,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x81],
  },
  '91': {
    fullName: 'STA_INDY',
    commandName: BaseName.STA,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x91],
  },
  '86': {
    fullName: 'STX_ZERO',
    commandName: BaseName.STX,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x86],
  },
  '8E': {
    fullName: 'STX_ABS',
    commandName: BaseName.STX,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x8e],
  },
  '96': {
    fullName: 'STX_ZEROY',
    commandName: BaseName.STX,
    mode: AddressingMode.ZERO_PAGE_Y,
    cycle: cycles[0x96],
  },
  '84': {
    fullName: 'STY_ZERO',
    commandName: BaseName.STY,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x84],
  },
  '8C': {
    fullName: 'STY_ABS',
    commandName: BaseName.STY,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x8c],
  },
  '94': {
    fullName: 'STY_ZEROX',
    commandName: BaseName.STY,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x94],
  },
  '8A': {
    fullName: 'TXA',
    commandName: BaseName.TXA,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x8a],
  },
  '98': {
    fullName: 'TYA',
    commandName: BaseName.TYA,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x98],
  },
  '9A': {
    fullName: 'TXS',
    commandName: BaseName.TXS,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x9a],
  },
  A8: {
    fullName: 'TAY',
    commandName: BaseName.TAY,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xa8],
  },
  AA: {
    fullName: 'TAX',
    commandName: BaseName.TAX,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xaa],
  },
  BA: {
    fullName: 'TSX',
    commandName: BaseName.TSX,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xba],
  },
  '8': {
    fullName: 'PHP',
    commandName: BaseName.PHP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x08],
  },
  '28': {
    fullName: 'PLP',
    commandName: BaseName.PLP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x28],
  },
  '48': {
    fullName: 'PHA',
    commandName: BaseName.PHA,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x48],
  },
  '68': {
    fullName: 'PLA',
    commandName: BaseName.PLA,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x68],
  },
  '69': {
    fullName: 'ADC_IMM',
    commandName: BaseName.ADC,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0x69],
  },
  '65': {
    fullName: 'ADC_ZERO',
    commandName: BaseName.ADC,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x65],
  },
  '6D': {
    fullName: 'ADC_ABS',
    commandName: BaseName.ADC,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x6d],
  },
  '75': {
    fullName: 'ADC_ZEROX',
    commandName: BaseName.ADC,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x75],
  },
  '7D': {
    fullName: 'ADC_ABSX',
    commandName: BaseName.ADC,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x7d],
  },
  '79': {
    fullName: 'ADC_ABSY',
    commandName: BaseName.ADC,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x79],
  },
  '61': {
    fullName: 'ADC_INDX',
    commandName: BaseName.ADC,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x61],
  },
  '71': {
    fullName: 'ADC_INDY',
    commandName: BaseName.ADC,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x71],
  },
  E9: {
    fullName: 'SBC_IMM',
    commandName: BaseName.SBC,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xe9],
  },
  E5: {
    fullName: 'SBC_ZERO',
    commandName: BaseName.SBC,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xe5],
  },
  ED: {
    fullName: 'SBC_ABS',
    commandName: BaseName.SBC,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xed],
  },
  F5: {
    fullName: 'SBC_ZEROX',
    commandName: BaseName.SBC,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xf5],
  },
  FD: {
    fullName: 'SBC_ABSX',
    commandName: BaseName.SBC,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xfd],
  },
  F9: {
    fullName: 'SBC_ABSY',
    commandName: BaseName.SBC,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0xf9],
  },
  E1: {
    fullName: 'SBC_INDX',
    commandName: BaseName.SBC,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0xe1],
  },
  F1: {
    fullName: 'SBC_INDY',
    commandName: BaseName.SBC,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0xf1],
  },
  E0: {
    fullName: 'CPX_IMM',
    commandName: BaseName.CPX,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xe0],
  },
  E4: {
    fullName: 'CPX_ZERO',
    commandName: BaseName.CPX,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xe4],
  },
  EC: {
    fullName: 'CPX_ABS',
    commandName: BaseName.CPX,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xec],
  },
  C0: {
    fullName: 'CPY_IMM',
    commandName: BaseName.CPY,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xc0],
  },
  C4: {
    fullName: 'CPY_ZERO',
    commandName: BaseName.CPY,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xc4],
  },
  CC: {
    fullName: 'CPY_ABS',
    commandName: BaseName.CPY,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xcc],
  },
  C9: {
    fullName: 'CMP_IMM',
    commandName: BaseName.CMP,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xc9],
  },
  C5: {
    fullName: 'CMP_ZERO',
    commandName: BaseName.CMP,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xc5],
  },
  CD: {
    fullName: 'CMP_ABS',
    commandName: BaseName.CMP,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xcd],
  },
  D5: {
    fullName: 'CMP_ZEROX',
    commandName: BaseName.CMP,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xd5],
  },
  DD: {
    fullName: 'CMP_ABSX',
    commandName: BaseName.CMP,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xdd],
  },
  D9: {
    fullName: 'CMP_ABSY',
    commandName: BaseName.CMP,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0xd9],
  },
  C1: {
    fullName: 'CMP_INDX',
    commandName: BaseName.CMP,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0xc1],
  },
  D1: {
    fullName: 'CMP_INDY',
    commandName: BaseName.CMP,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0xd1],
  },
  '29': {
    fullName: 'AND_IMM',
    commandName: BaseName.AND,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0x29],
  },
  '25': {
    fullName: 'AND_ZERO',
    commandName: BaseName.AND,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x25],
  },
  '2D': {
    fullName: 'AND_ABS',
    commandName: BaseName.AND,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x2d],
  },
  '35': {
    fullName: 'AND_ZEROX',
    commandName: BaseName.AND,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x35],
  },
  '3D': {
    fullName: 'AND_ABSX',
    commandName: BaseName.AND,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x3d],
  },
  '39': {
    fullName: 'AND_ABSY',
    commandName: BaseName.AND,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x39],
  },
  '21': {
    fullName: 'AND_INDX',
    commandName: BaseName.AND,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x21],
  },
  '31': {
    fullName: 'AND_INDY',
    commandName: BaseName.AND,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x31],
  },
  '49': {
    fullName: 'EOR_IMM',
    commandName: BaseName.EOR,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0x49],
  },
  '45': {
    fullName: 'EOR_ZERO',
    commandName: BaseName.EOR,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x45],
  },
  '4D': {
    fullName: 'EOR_ABS',
    commandName: BaseName.EOR,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x4d],
  },
  '55': {
    fullName: 'EOR_ZEROX',
    commandName: BaseName.EOR,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x55],
  },
  '5D': {
    fullName: 'EOR_ABSX',
    commandName: BaseName.EOR,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x5d],
  },
  '59': {
    fullName: 'EOR_ABSY',
    commandName: BaseName.EOR,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x59],
  },
  '41': {
    fullName: 'EOR_INDX',
    commandName: BaseName.EOR,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x41],
  },
  '51': {
    fullName: 'EOR_INDY',
    commandName: BaseName.EOR,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x51],
  },
  '9': {
    fullName: 'ORA_IMM',
    commandName: BaseName.ORA,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0x09],
  },
  '5': {
    fullName: 'ORA_ZERO',
    commandName: BaseName.ORA,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x05],
  },
  D: {
    fullName: 'ORA_ABS',
    commandName: BaseName.ORA,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x0d],
  },
  '15': {
    fullName: 'ORA_ZEROX',
    commandName: BaseName.ORA,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x15],
  },
  '1D': {
    fullName: 'ORA_ABSX',
    commandName: BaseName.ORA,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x1d],
  },
  '19': {
    fullName: 'ORA_ABSY',
    commandName: BaseName.ORA,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x19],
  },
  '1': {
    fullName: 'ORA_INDX',
    commandName: BaseName.ORA,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x01],
  },
  '11': {
    fullName: 'ORA_INDY',
    commandName: BaseName.ORA,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x11],
  },
  '24': {
    fullName: 'BIT_ZERO',
    commandName: BaseName.BIT,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x24],
  },
  '2C': {
    fullName: 'BIT_ABS',
    commandName: BaseName.BIT,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x2c],
  },
  A: {
    fullName: 'ASL',
    commandName: BaseName.ASL,
    mode: AddressingMode.ACCUMULATOR,
    cycle: cycles[0x0a],
  },
  '6': {
    fullName: 'ASL_ZERO',
    commandName: BaseName.ASL,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x06],
  },
  E: {
    fullName: 'ASL_ABS',
    commandName: BaseName.ASL,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x0e],
  },
  '16': {
    fullName: 'ASL_ZEROX',
    commandName: BaseName.ASL,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x16],
  },
  '1E': {
    fullName: 'ASL_ABSX',
    commandName: BaseName.ASL,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x1e],
  },
  '4A': {
    fullName: 'LSR',
    commandName: BaseName.LSR,
    mode: AddressingMode.ACCUMULATOR,
    cycle: cycles[0x4a],
  },
  '46': {
    fullName: 'LSR_ZERO',
    commandName: BaseName.LSR,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x46],
  },
  '4E': {
    fullName: 'LSR_ABS',
    commandName: BaseName.LSR,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x4e],
  },
  '56': {
    fullName: 'LSR_ZEROX',
    commandName: BaseName.LSR,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x56],
  },
  '5E': {
    fullName: 'LSR_ABSX',
    commandName: BaseName.LSR,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x5e],
  },
  '2A': {
    fullName: 'ROL',
    commandName: BaseName.ROL,
    mode: AddressingMode.ACCUMULATOR,
    cycle: cycles[0x2a],
  },
  '26': {
    fullName: 'ROL_ZERO',
    commandName: BaseName.ROL,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x26],
  },
  '2E': {
    fullName: 'ROL_ABS',
    commandName: BaseName.ROL,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x2e],
  },
  '36': {
    fullName: 'ROL_ZEROX',
    commandName: BaseName.ROL,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x36],
  },
  '3E': {
    fullName: 'ROL_ABSX',
    commandName: BaseName.ROL,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x3e],
  },
  '6A': {
    fullName: 'ROR',
    commandName: BaseName.ROR,
    mode: AddressingMode.ACCUMULATOR,
    cycle: cycles[0x6a],
  },
  '66': {
    fullName: 'ROR_ZERO',
    commandName: BaseName.ROR,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x66],
  },
  '6E': {
    fullName: 'ROR_ABS',
    commandName: BaseName.ROR,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x6e],
  },
  '76': {
    fullName: 'ROR_ZEROX',
    commandName: BaseName.ROR,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x76],
  },
  '7E': {
    fullName: 'ROR_ABSX',
    commandName: BaseName.ROR,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x7e],
  },
  E8: {
    fullName: 'INX',
    commandName: BaseName.INX,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xe8],
  },
  C8: {
    fullName: 'INY',
    commandName: BaseName.INY,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xc8],
  },
  E6: {
    fullName: 'INC_ZERO',
    commandName: BaseName.INC,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xe6],
  },
  EE: {
    fullName: 'INC_ABS',
    commandName: BaseName.INC,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xee],
  },
  F6: {
    fullName: 'INC_ZEROX',
    commandName: BaseName.INC,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xf6],
  },
  FE: {
    fullName: 'INC_ABSX',
    commandName: BaseName.INC,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xfe],
  },
  CA: {
    fullName: 'DEX',
    commandName: BaseName.DEX,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xca],
  },
  '88': {
    fullName: 'DEY',
    commandName: BaseName.DEY,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x88],
  },
  C6: {
    fullName: 'DEC_ZERO',
    commandName: BaseName.DEC,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xc6],
  },
  CE: {
    fullName: 'DEC_ABS',
    commandName: BaseName.DEC,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xce],
  },
  D6: {
    fullName: 'DEC_ZEROX',
    commandName: BaseName.DEC,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xd6],
  },
  DE: {
    fullName: 'DEC_ABSX',
    commandName: BaseName.DEC,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xde],
  },
  '18': {
    fullName: 'CLC',
    commandName: BaseName.CLC,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x18],
  },
  '58': {
    fullName: 'CLI',
    commandName: BaseName.CLI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x58],
  },
  B8: {
    fullName: 'CLV',
    commandName: BaseName.CLV,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xb8],
  },
  '38': {
    fullName: 'SEC',
    commandName: BaseName.SEC,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x38],
  },
  '78': {
    fullName: 'SEI',
    commandName: BaseName.SEI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x78],
  },
  EA: {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xea],
  },
  '0': {
    fullName: 'BRK',
    commandName: BaseName.BRK,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x00],
  },
  '20': {
    fullName: 'JSR_ABS',
    commandName: BaseName.JSR,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x20],
  },
  '4C': {
    fullName: 'JMP_ABS',
    commandName: BaseName.JMP,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x4c],
  },
  '6C': {
    fullName: 'JMP_INDABS',
    commandName: BaseName.JMP,
    mode: AddressingMode.INDIRECT_ABSOLUTE,
    cycle: cycles[0x6c],
  },
  '40': {
    fullName: 'RTI',
    commandName: BaseName.RTI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x40],
  },
  '60': {
    fullName: 'RTS',
    commandName: BaseName.RTS,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x60],
  },
  '10': {
    fullName: 'BPL',
    commandName: BaseName.BPL,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0x10],
  },
  '30': {
    fullName: 'BMI',
    commandName: BaseName.BMI,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0x30],
  },
  '50': {
    fullName: 'BVC',
    commandName: BaseName.BVC,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0x50],
  },
  '70': {
    fullName: 'BVS',
    commandName: BaseName.BVS,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0x70],
  },
  '90': {
    fullName: 'BCC',
    commandName: BaseName.BCC,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0x90],
  },
  B0: {
    fullName: 'BCS',
    commandName: BaseName.BCS,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0xb0],
  },
  D0: {
    fullName: 'BNE',
    commandName: BaseName.BNE,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0xd0],
  },
  F0: {
    fullName: 'BEQ',
    commandName: BaseName.BEQ,
    mode: AddressingMode.RELATIVE,
    cycle: cycles[0xf0],
  },
  F8: {
    fullName: 'SED',
    commandName: BaseName.SED,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xf8],
  },
  D8: {
    fullName: 'CLD',
    commandName: BaseName.CLD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xd8],
  },
  // unofficial opecode
  // Also see https://wiki.nesdev.com/w/index.php/CPU_unofficial_opcodes
  '1A': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x1a],
  },
  '3A': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x3a],
  },
  '5A': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x5a],
  },
  '7A': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x7a],
  },
  DA: {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xda],
  },
  FA: {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xfa],
  },

  '02': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x02],
  },
  '12': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x12],
  },
  '22': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x22],
  },
  '32': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x32],
  },
  '42': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x42],
  },
  '52': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x52],
  },
  '62': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x62],
  },
  '72': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x72],
  },
  '92': {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x92],
  },
  B2: {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xb2],
  },
  D2: {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xd2],
  },
  F2: {
    fullName: 'NOP',
    commandName: BaseName.NOP,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xf2],
  },

  '80': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x80],
  },
  '82': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x82],
  },
  '89': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x89],
  },
  C2: {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xc2],
  },
  E2: {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xe2],
  },
  '04': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x04],
  },
  '44': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x44],
  },
  '64': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x64],
  },
  '14': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x14],
  },
  '34': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x34],
  },
  '54': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x54],
  },
  '74': {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x74],
  },
  D4: {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xd4],
  },
  F4: {
    fullName: 'NOPD',
    commandName: BaseName.NOPD,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xf4],
  },

  '0C': {
    fullName: 'NOPI',
    commandName: BaseName.NOPI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x0c],
  },
  '1C': {
    fullName: 'NOPI',
    commandName: BaseName.NOPI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x1c],
  },
  '3C': {
    fullName: 'NOPI',
    commandName: BaseName.NOPI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x3c],
  },
  '5C': {
    fullName: 'NOPI',
    commandName: BaseName.NOPI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x5c],
  },
  '7C': {
    fullName: 'NOPI',
    commandName: BaseName.NOPI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0x7c],
  },
  DC: {
    fullName: 'NOPI',
    commandName: BaseName.NOPI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xdc],
  },
  FC: {
    fullName: 'NOPI',
    commandName: BaseName.NOPI,
    mode: AddressingMode.IMPLIED,
    cycle: cycles[0xfc],
  },
  // LAX
  A7: {
    fullName: 'LAX_ZERO',
    commandName: BaseName.LAX,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xa7],
  },
  B7: {
    fullName: 'LAX_ZEROY',
    commandName: BaseName.LAX,
    mode: AddressingMode.ZERO_PAGE_Y,
    cycle: cycles[0xb7],
  },
  AF: {
    fullName: 'LAX_ABS',
    commandName: BaseName.LAX,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xaf],
  },
  BF: {
    fullName: 'LAX_ABSY',
    commandName: BaseName.LAX,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0xbf],
  },
  A3: {
    fullName: 'LAX_INDX',
    commandName: BaseName.LAX,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0xa3],
  },
  B3: {
    fullName: 'LAX_INDY',
    commandName: BaseName.LAX,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0xb3],
  },
  // SAX
  '87': {
    fullName: 'SAX_ZERO',
    commandName: BaseName.SAX,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x87],
  },
  '97': {
    fullName: 'SAX_ZEROY',
    commandName: BaseName.SAX,
    mode: AddressingMode.ZERO_PAGE_Y,
    cycle: cycles[0x97],
  },
  '8F': {
    fullName: 'SAX_ABS',
    commandName: BaseName.SAX,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x8f],
  },
  '83': {
    fullName: 'SAX_INDX',
    commandName: BaseName.SAX,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x83],
  },
  // SBC
  EB: {
    fullName: 'SBC_IMM',
    commandName: BaseName.SBC,
    mode: AddressingMode.IMMEDIATE,
    cycle: cycles[0xeb],
  },
  // DCP
  C7: {
    fullName: 'DCP_ZERO',
    commandName: BaseName.DCP,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xc7],
  },
  D7: {
    fullName: 'DCP_ZEROX',
    commandName: BaseName.DCP,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xd7],
  },
  CF: {
    fullName: 'DCP_ABS',
    commandName: BaseName.DCP,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xcf],
  },
  DF: {
    fullName: 'DCP_ABSX',
    commandName: BaseName.DCP,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xdf],
  },
  DB: {
    fullName: 'DCP_ABSY',
    commandName: BaseName.DCP,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0xd8],
  },
  C3: {
    fullName: 'DCP_INDX',
    commandName: BaseName.DCP,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0xc3],
  },
  D3: {
    fullName: 'DCP_INDY',
    commandName: BaseName.DCP,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0xd3],
  },
  // ISB
  E7: {
    fullName: 'ISB_ZERO',
    commandName: BaseName.ISB,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0xe7],
  },
  F7: {
    fullName: 'ISB_ZEROX',
    commandName: BaseName.ISB,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0xf7],
  },
  EF: {
    fullName: 'ISB_ABS',
    commandName: BaseName.ISB,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0xef],
  },
  FF: {
    fullName: 'ISB_ABSX',
    commandName: BaseName.ISB,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0xff],
  },
  FB: {
    fullName: 'ISB_ABSY',
    commandName: BaseName.ISB,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0xf8],
  },
  E3: {
    fullName: 'ISB_INDX',
    commandName: BaseName.ISB,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0xe3],
  },
  F3: {
    fullName: 'ISB_INDY',
    commandName: BaseName.ISB,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0xf3],
  },
  // SLO
  '07': {
    fullName: 'SLO_ZERO',
    commandName: BaseName.SLO,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x07],
  },
  '17': {
    fullName: 'SLO_ZEROX',
    commandName: BaseName.SLO,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x17],
  },
  '0F': {
    fullName: 'SLO_ABS',
    commandName: BaseName.SLO,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x0f],
  },
  '1F': {
    fullName: 'SLO_ABSX',
    commandName: BaseName.SLO,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x1f],
  },
  '1B': {
    fullName: 'SLO_ABSY',
    commandName: BaseName.SLO,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x1b],
  },
  '03': {
    fullName: 'SLO_INDX',
    commandName: BaseName.SLO,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x03],
  },
  '13': {
    fullName: 'SLO_INDY',
    commandName: BaseName.SLO,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x13],
  },
  // RLA
  '27': {
    fullName: 'RLA_ZERO',
    commandName: BaseName.RLA,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x27],
  },
  '37': {
    fullName: 'RLA_ZEROX',
    commandName: BaseName.RLA,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x37],
  },
  '2F': {
    fullName: 'RLA_ABS',
    commandName: BaseName.RLA,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x2f],
  },
  '3F': {
    fullName: 'RLA_ABSX',
    commandName: BaseName.RLA,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x3f],
  },
  '3B': {
    fullName: 'RLA_ABSY',
    commandName: BaseName.RLA,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x3b],
  },
  '23': {
    fullName: 'RLA_INDX',
    commandName: BaseName.RLA,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x23],
  },
  '33': {
    fullName: 'RLA_INDY',
    commandName: BaseName.RLA,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x33],
  },
  // SRE
  '47': {
    fullName: 'SRE_ZERO',
    commandName: BaseName.SRE,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x47],
  },
  '57': {
    fullName: 'SRE_ZEROX',
    commandName: BaseName.SRE,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x57],
  },
  '4F': {
    fullName: 'SRE_ABS',
    commandName: BaseName.SRE,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x4f],
  },
  '5F': {
    fullName: 'SRE_ABSX',
    commandName: BaseName.SRE,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x5f],
  },
  '5B': {
    fullName: 'SRE_ABSY',
    commandName: BaseName.SRE,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x5b],
  },
  '43': {
    fullName: 'SRE_INDX',
    commandName: BaseName.SRE,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x43],
  },
  '53': {
    fullName: 'SRE_INDY',
    commandName: BaseName.SRE,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x53],
  },
  // RRA
  '67': {
    fullName: 'RRA_ZERO',
    commandName: BaseName.RRA,
    mode: AddressingMode.ZERO_PAGE,
    cycle: cycles[0x67],
  },
  '77': {
    fullName: 'RRA_ZEROX',
    commandName: BaseName.RRA,
    mode: AddressingMode.ZERO_PAGE_X,
    cycle: cycles[0x77],
  },
  '6F': {
    fullName: 'RRA_ABS',
    commandName: BaseName.RRA,
    mode: AddressingMode.ABSOLUTE,
    cycle: cycles[0x6f],
  },
  '7F': {
    fullName: 'RRA_ABSX',
    commandName: BaseName.RRA,
    mode: AddressingMode.ABSOLUTE_X,
    cycle: cycles[0x7f],
  },
  '7B': {
    fullName: 'RRA_ABSY',
    commandName: BaseName.RRA,
    mode: AddressingMode.ABSOLUTE_Y,
    cycle: cycles[0x7b],
  },
  '63': {
    fullName: 'RRA_INDX',
    commandName: BaseName.RRA,
    mode: AddressingMode.PRE_INDEXED_INDIRECT,
    cycle: cycles[0x63],
  },
  '73': {
    fullName: 'RRA_INDY',
    commandName: BaseName.RRA,
    mode: AddressingMode.POST_INDEXED_INDIRECT,
    cycle: cycles[0x73],
  },
}

/**
 * オペコードList作成
 *
 * @returns opeCodeList
 */
const initOpeCodeList = (): Array<OpecodeProps> => {
  const opeCodeList: Array<OpecodeProps> = []
  Object.keys(dict).forEach((key: string) => {
    const { fullName, commandName: baseName, mode, cycle } = dict[key]
    opeCodeList[parseInt(key, 16)] = {
      fullName,
      commandName: baseName,
      mode,
      cycle,
    }
  })
  return opeCodeList
}

export default initOpeCodeList
